/**
 * CodeByTushu Store - Product Data
 * Auto-generated by script for 90 unique products
 */

const storeData = [
    {
        "id": "after-effects-templates-01",
        "title": "After Effects Templates",
        "category": "Digital Templates",
        "price": 1499,
        "rating": "4.7",
        "reviews": 142,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/after-effects-templates-01.png",
        "gallery": [
            "../Store Product Images/after-effects-templates-01.png"
        ],
        "description": "Professional After Effects templates to elevate your video production. Perfect for content creators and motion designers.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "backpack-01",
        "title": "Backpack",
        "category": "Accessories",
        "price": 1999,
        "rating": "5.0",
        "reviews": 237,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/backpack-01.png",
        "gallery": [
            "../Store Product Images/backpack-01.png"
        ],
        "description": "Durable and spacious backpack designed for developers on the go. Features multiple compartments for laptops, gadgets, and everyday essentials.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "baseball-cap-01",
        "title": "Baseball Cap",
        "category": "Accessories",
        "price": 499,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/baseball-cap-01.png",
        "gallery": [
            "../Store Product Images/baseball-cap-01.png"
        ],
        "description": "Stylish and comfortable baseball cap with a subtle developer-themed logo. Perfect for casual wear or sunny outdoor coding sessions.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "bomber-jacket-01",
        "title": "Bomber Jacket",
        "category": "Hoodies",
        "price": 2499,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/bomber-jacket-01.png",
        "gallery": [
            "../Store Product Images/bomber-jacket-01.png"
        ],
        "description": "Premium bomber jacket combining street style with tech culture. Keep warm while looking sharp during your late-night coding marathons.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "cable-organizer-01",
        "title": "Cable Organizer",
        "category": "Accessories",
        "price": 299,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/cable-organizer-01.png",
        "gallery": [
            "../Store Product Images/cable-organizer-01.png"
        ],
        "description": "Keep your workspace clutter-free with this sleek cable organizer. Perfect for managing charging cables, USB cords, and peripheral wires.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "career-guidance-01",
        "title": "Career Guidance",
        "category": "Services",
        "price": 999,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/career-guidance-01.png",
        "gallery": [
            "../Store Product Images/career-guidance-01.png"
        ],
        "description": "Expert career guidance session tailored for aspiring developers. Get actionable advice on resume building, interviews, and career progression.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "career-roadmaps-01",
        "title": "Career Roadmaps",
        "category": "E-books",
        "price": 299,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/career-roadmaps-01.png",
        "gallery": [
            "../Store Product Images/career-roadmaps-01.png"
        ],
        "description": "Comprehensive career roadmaps for various tech domains including Frontend, Backend, DevOps, and Data Science. Your step-by-step guide to success.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "cheat-sheets-01",
        "title": "Cheat Sheets",
        "category": "E-books",
        "price": 199,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/cheat-sheets-01.png",
        "gallery": [
            "../Store Product Images/cheat-sheets-01.png"
        ],
        "description": "High-quality developer cheat sheets covering HTML, CSS, JavaScript, Git, and more. A quick reference guide for your everyday coding needs.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "coffee-mug-01",
        "title": "Coffee Mug",
        "category": "Mugs",
        "price": 399,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/coffee-mug-01.png",
        "gallery": [
            "../Store Product Images/coffee-mug-01.png"
        ],
        "description": "Classic ceramic coffee mug for your daily caffeine fix. Features a witty coding joke to start your morning right.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "cover-letter-templates-01",
        "title": "Cover Letter Templates",
        "category": "Digital Templates",
        "price": 149,
        "rating": "4.6",
        "reviews": 125,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/cover-letter-templates-01.png",
        "gallery": [
            "../Store Product Images/cover-letter-templates-01.png"
        ],
        "description": "Professional cover letter templates designed specifically for tech roles. Stand out to recruiters with a clean and impactful design.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-calendar-01",
        "title": "Desk Calendar",
        "category": "Accessories",
        "price": 249,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-calendar-01.png",
        "gallery": [
            "../Store Product Images/desk-calendar-01.png"
        ],
        "description": "Minimalist desk calendar to help you track project deadlines and milestones. A perfect addition to any productive workspace.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-clock-01",
        "title": "Desk Clock",
        "category": "Accessories",
        "price": 899,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-clock-01.png",
        "gallery": [
            "../Store Product Images/desk-clock-01.png"
        ],
        "description": "Modern digital desk clock with temperature and humidity display. Keep track of time during intense coding sessions in style.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-mat-01",
        "title": "Desk Mat",
        "category": "Accessories",
        "price": 799,
        "rating": "5.0",
        "reviews": 237,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-mat-01.png",
        "gallery": [
            "../Store Product Images/desk-mat-01.png"
        ],
        "description": "Large, anti-slip desk mat providing a smooth surface for your mouse and keyboard. Enhances desk aesthetics and protects your workspace.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-organizer-01",
        "title": "Desk Organizer",
        "category": "Accessories",
        "price": 599,
        "rating": "5.0",
        "reviews": 339,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-organizer-01.png",
        "gallery": [
            "../Store Product Images/desk-organizer-01.png"
        ],
        "description": "Multi-compartment desk organizer to keep your pens, flash drives, and small gadgets neatly arranged. Maximize your desk space.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-plant-01",
        "title": "Desk Plant",
        "category": "Accessories",
        "price": 349,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-plant-01.png",
        "gallery": [
            "../Store Product Images/desk-plant-01.png"
        ],
        "description": "Low-maintenance artificial desk plant to bring a touch of greenery and calm to your workstation without the hassle of watering.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "developer-quote-stickers-01",
        "title": "Developer Quote Stickers",
        "category": "Stickers",
        "price": 149,
        "rating": "4.8",
        "reviews": 159,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/developer-quote-stickers-01.png",
        "gallery": [
            "../Store Product Images/developer-quote-stickers-01.png"
        ],
        "description": "Pack of high-quality vinyl stickers featuring relatable and humorous developer quotes. Perfect for customizing your laptop or workspace.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "developer-stickers-01",
        "title": "Developer Stickers",
        "category": "Stickers",
        "price": 199,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/developer-stickers-01.png",
        "gallery": [
            "../Store Product Images/developer-stickers-01.png"
        ],
        "description": "Assorted collection of popular programming languages and framework logos. Show off your tech stack with these durable laptop stickers.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "devops-course-01",
        "title": "Devops Course",
        "category": "Courses",
        "price": 3999,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/devops-course-01.png",
        "gallery": [
            "../Store Product Images/devops-course-01.png"
        ],
        "description": "Comprehensive DevOps course covering CI/CD, Docker, Kubernetes, and AWS. Master modern deployment pipelines and infrastructure.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "dsa-course-01",
        "title": "Dsa Course",
        "category": "Courses",
        "price": 2999,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/dsa-course-01.png",
        "gallery": [
            "../Store Product Images/dsa-course-01.png"
        ],
        "description": "Deep dive into Data Structures and Algorithms. Crack your technical interviews with confidence through hands-on problem solving.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "e-book-collection-01",
        "title": "E Book Collection",
        "category": "E-books",
        "price": 999,
        "rating": "4.7",
        "reviews": 390,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/e-book-collection-01.png",
        "gallery": [
            "../Store Product Images/e-book-collection-01.png"
        ],
        "description": "A curated collection of top-rated E-books covering modern web development, clean code practices, and system design principles.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "ergonomic-chair-01",
        "title": "Ergonomic Chair",
        "category": "Accessories",
        "price": 8999,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/ergonomic-chair-01.png",
        "gallery": [
            "../Store Product Images/ergonomic-chair-01.png"
        ],
        "description": "Premium ergonomic office chair with lumbar support and adjustable armrests. Prevent back pain during long hours of coding.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "extended-mouse-pad-01",
        "title": "Extended Mouse Pad",
        "category": "Accessories",
        "price": 699,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/extended-mouse-pad-01.png",
        "gallery": [
            "../Store Product Images/extended-mouse-pad-01.png"
        ],
        "description": "Extended gaming-grade mouse pad featuring a sleek dark theme. Provides ultimate precision and comfort for long working hours.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "extended-mouse-pad-03",
        "title": "Extended Mouse Pad",
        "category": "Accessories",
        "price": 699,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/extended-mouse-pad-03.png",
        "gallery": [
            "../Store Product Images/extended-mouse-pad-03.png"
        ],
        "description": "Premium extended mouse pad with stitched edges and a waterproof surface. Ideal for developers who prefer a clean, minimal desk setup.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "figma-templates-01",
        "title": "Figma Templates",
        "category": "Digital Templates",
        "price": 1299,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/figma-templates-01.png",
        "gallery": [
            "../Store Product Images/figma-templates-01.png"
        ],
        "description": "High-fidelity Figma UI templates for web and mobile apps. Accelerate your design process with these ready-to-use component libraries.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "framed-poster-01",
        "title": "Framed Poster",
        "category": "Accessories",
        "price": 899,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/framed-poster-01.png",
        "gallery": [
            "../Store Product Images/framed-poster-01.png"
        ],
        "description": "High-quality framed poster featuring motivational tech artwork. Add a professional and inspiring touch to your home office wall.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "freelancing-consultation-01",
        "title": "Freelancing Consultation",
        "category": "Services",
        "price": 1499,
        "rating": "4.8",
        "reviews": 159,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/freelancing-consultation-01.png",
        "gallery": [
            "../Store Product Images/freelancing-consultation-01.png"
        ],
        "description": "One-on-one consultation to jumpstart your freelance career. Learn how to find clients, price your services, and build a strong portfolio.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "full-stack-web-development-01",
        "title": "Full Stack Web Development",
        "category": "Courses",
        "price": 4999,
        "rating": "5.0",
        "reviews": 193,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/full-stack-web-development-01.png",
        "gallery": [
            "../Store Product Images/full-stack-web-development-01.png"
        ],
        "description": "The ultimate Full Stack Web Development bootcamp. Learn MERN stack from scratch and build production-ready applications.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "hoodie-01",
        "title": "Hoodie",
        "category": "Hoodies",
        "price": 1499,
        "rating": "4.8",
        "reviews": 203,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/hoodie-01.png",
        "gallery": [
            "../Store Product Images/hoodie-01.png"
        ],
        "description": "Extremely comfortable and warm hoodie with a minimalist developer logo. The ultimate uniform for late-night debugging.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "icons-pack-01",
        "title": "Icons Pack",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/icons-pack-01.png",
        "gallery": [
            "../Store Product Images/icons-pack-01.png"
        ],
        "description": "Comprehensive pack of premium SVG icons tailored for tech and startup websites. Clean, scalable, and easy to integrate.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "interview-preparation-course-01",
        "title": "Interview Preparation Course",
        "category": "Courses",
        "price": 1999,
        "rating": "4.6",
        "reviews": 227,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/interview-preparation-course-01.png",
        "gallery": [
            "../Store Product Images/interview-preparation-course-01.png"
        ],
        "description": "Complete interview preparation course covering HR rounds, technical questions, and mock interviews to help you land your dream job.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "interview-preparation-guide-01",
        "title": "Interview Preparation Guide",
        "category": "E-books",
        "price": 399,
        "rating": "4.5",
        "reviews": 210,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/interview-preparation-guide-01.png",
        "gallery": [
            "../Store Product Images/interview-preparation-guide-01.png"
        ],
        "description": "A detailed guide packed with the most frequently asked technical interview questions, optimal solutions, and negotiation tips.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "java-masterclass-01",
        "title": "Java Masterclass",
        "category": "Courses",
        "price": 2499,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/java-masterclass-01.png",
        "gallery": [
            "../Store Product Images/java-masterclass-01.png"
        ],
        "description": "Master Java programming from basic concepts to advanced multithreading and Spring Boot framework integration.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "javascript-masterclass-01",
        "title": "Javascript Masterclass",
        "category": "Courses",
        "price": 2499,
        "rating": "4.6",
        "reviews": 125,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/javascript-masterclass-01.png",
        "gallery": [
            "../Store Product Images/javascript-masterclass-01.png"
        ],
        "description": "In-depth JavaScript masterclass covering ES6+, async programming, closures, and modern DOM manipulation techniques.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "javascript-notes-pdf-01",
        "title": "Javascript Notes Pdf",
        "category": "E-books",
        "price": 199,
        "rating": "5.0",
        "reviews": 91,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/javascript-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/javascript-notes-pdf-01.png"
        ],
        "description": "Handwritten-style digital notes for JavaScript. Simplifies complex topics into easily digestible visual explanations.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "keyboard-stickers-01",
        "title": "Keyboard Stickers",
        "category": "Stickers",
        "price": 149,
        "rating": "4.7",
        "reviews": 390,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/keyboard-stickers-01.png",
        "gallery": [
            "../Store Product Images/keyboard-stickers-01.png"
        ],
        "description": "Shortcut keyboard stickers to boost your productivity. Master your IDE and OS shortcuts with these durable, easy-to-apply decals.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "landing-page-templates-01",
        "title": "Landing Page Templates",
        "category": "Digital Templates",
        "price": 899,
        "rating": "4.6",
        "reviews": 125,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/landing-page-templates-01.png",
        "gallery": [
            "../Store Product Images/landing-page-templates-01.png"
        ],
        "description": "Conversion-optimized HTML/CSS landing page templates. Launch your startup or portfolio quickly with responsive, clean code.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-bag-01",
        "title": "Laptop Bag",
        "category": "Accessories",
        "price": 1299,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/laptop-bag-01.png",
        "gallery": [
            "../Store Product Images/laptop-bag-01.png"
        ],
        "description": "Stylish and protective laptop bag with water-resistant fabric. Safely carry your tech gear with multiple padded compartments.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-skin-01",
        "title": "Laptop Skin",
        "category": "Accessories",
        "price": 399,
        "rating": "4.7",
        "reviews": 288,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/laptop-skin-01.png",
        "gallery": [
            "../Store Product Images/laptop-skin-01.png"
        ],
        "description": "Premium vinyl laptop skin featuring a sleek carbon fiber texture. Protect your device from scratches while adding a touch of style.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-sleeve-01",
        "title": "Laptop Sleeve",
        "category": "Accessories",
        "price": 599,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/laptop-sleeve-01.png",
        "gallery": [
            "../Store Product Images/laptop-sleeve-01.png"
        ],
        "description": "Slim and lightweight laptop sleeve with soft fleece lining. Provides excellent protection against dust, bumps, and accidental drops.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-stand-01",
        "title": "Laptop Stand",
        "category": "Accessories",
        "price": 899,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/laptop-stand-01.png",
        "gallery": [
            "../Store Product Images/laptop-stand-01.png"
        ],
        "description": "Ergonomic aluminum laptop stand to elevate your screen to eye level. Improves posture and enhances laptop cooling.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-stickers-01",
        "title": "Laptop Stickers",
        "category": "Stickers",
        "price": 249,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/laptop-stickers-01.png",
        "gallery": [
            "../Store Product Images/laptop-stickers-01.png"
        ],
        "description": "A massive pack of diverse tech and pop-culture stickers to fully personalize the lid of your laptop. High quality and residue-free.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "linux-course-01",
        "title": "Linux Course",
        "category": "Courses",
        "price": 1499,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/linux-course-01.png",
        "gallery": [
            "../Store Product Images/linux-course-01.png"
        ],
        "description": "Master Linux command line, shell scripting, and system administration. Essential skills for every backend developer and DevOps engineer.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "long-sleeve-tshirt-01",
        "title": "Long Sleeve Tshirt",
        "category": "T-Shirts",
        "price": 699,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/long-sleeve-tshirt-01.png",
        "gallery": [
            "../Store Product Images/long-sleeve-tshirt-01.png"
        ],
        "description": "Comfortable long-sleeve t-shirt for breezy days. Features a subtle, elegant design that screams code without being loud.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "lower-thirds-01",
        "title": "Lower Thirds",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/lower-thirds-01.png",
        "gallery": [
            "../Store Product Images/lower-thirds-01.png"
        ],
        "description": "Professional lower thirds templates for Premiere Pro and After Effects. Perfect for YouTube tutorials, interviews, and vlogs.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "luts-01",
        "title": "Luts",
        "category": "Digital Templates",
        "price": 399,
        "rating": "4.6",
        "reviews": 169,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/luts-01.png",
        "gallery": [
            "../Store Product Images/luts-01.png"
        ],
        "description": "Cinematic color grading LUTs pack to instantly enhance your video projects. Compatible with all major video editing software.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "magic-mug-01",
        "title": "Magic Mug",
        "category": "Mugs",
        "price": 499,
        "rating": "4.5",
        "reviews": 254,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/magic-mug-01.png",
        "gallery": [
            "../Store Product Images/magic-mug-01.png"
        ],
        "description": "Heat-sensitive magic mug that reveals a hidden developer joke or code snippet when filled with hot coffee or tea.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mentorship-01",
        "title": "Mentorship",
        "category": "Services",
        "price": 4999,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mentorship-01.png",
        "gallery": [
            "../Store Product Images/mentorship-01.png"
        ],
        "description": "One-month exclusive mentorship program. Get personalized code reviews, architecture discussions, and career guidance from industry experts.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mobile-cover-01",
        "title": "Mobile Cover",
        "category": "Accessories",
        "price": 299,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/mobile-cover-01.png",
        "gallery": [
            "../Store Product Images/mobile-cover-01.png"
        ],
        "description": "Durable, shock-absorbing mobile cover featuring an exclusive circuit board design. Protect your phone in tech-inspired style.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mock-interview-01",
        "title": "Mock Interview",
        "category": "Services",
        "price": 899,
        "rating": "5.0",
        "reviews": 339,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mock-interview-01.png",
        "gallery": [
            "../Store Product Images/mock-interview-01.png"
        ],
        "description": "1-hour rigorous technical mock interview with actionable feedback. Identify your weak points and improve your problem-solving under pressure.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "motion-graphics-pack-01",
        "title": "Motion Graphics Pack",
        "category": "Digital Templates",
        "price": 1999,
        "rating": "5.0",
        "reviews": 91,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/motion-graphics-pack-01.png",
        "gallery": [
            "../Store Product Images/motion-graphics-pack-01.png"
        ],
        "description": "Massive pack of pre-animated motion graphics including transitions, titles, and backgrounds to supercharge your video editing.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mouse-pad-01",
        "title": "Mouse Pad",
        "category": "Accessories",
        "price": 249,
        "rating": "4.5",
        "reviews": 254,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mouse-pad-01.png",
        "gallery": [
            "../Store Product Images/mouse-pad-01.png"
        ],
        "description": "Standard size, high-precision mouse pad with a non-slip rubber base. Ideal for everyday browsing and precise UI/UX design work.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "nodejs-masterclass-01",
        "title": "Nodejs Masterclass",
        "category": "Courses",
        "price": 2499,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/nodejs-masterclass-01.png",
        "gallery": [
            "../Store Product Images/nodejs-masterclass-01.png"
        ],
        "description": "Complete Node.js masterclass covering Express, MongoDB, authentication, and REST API development. Build scalable backend systems.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "nodejs-notes-pdf-01",
        "title": "Nodejs Notes Pdf",
        "category": "E-books",
        "price": 199,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/nodejs-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/nodejs-notes-pdf-01.png"
        ],
        "description": "Comprehensive PDF notes on Node.js and Express. Detailed explanations of the event loop, streams, and backend architecture.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "notebook-01",
        "title": "Notebook",
        "category": "Accessories",
        "price": 299,
        "rating": "5.0",
        "reviews": 237,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/notebook-01.png",
        "gallery": [
            "../Store Product Images/notebook-01.png"
        ],
        "description": "High-quality dot-grid notebook, perfect for sketching out UI wireframes, algorithm logic, or taking meeting notes.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "oversized-tshirt-01",
        "title": "Oversized Tshirt",
        "category": "T-Shirts",
        "price": 699,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/oversized-tshirt-01.png",
        "gallery": [
            "../Store Product Images/oversized-tshirt-01.png"
        ],
        "description": "Trendy oversized t-shirt made from heavy cotton. Maximum comfort for long coding sessions or casual meetups.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "phone-stand-01",
        "title": "Phone Stand",
        "category": "Accessories",
        "price": 199,
        "rating": "4.7",
        "reviews": 288,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/phone-stand-01.png",
        "gallery": [
            "../Store Product Images/phone-stand-01.png"
        ],
        "description": "Adjustable desktop phone stand. Perfect for keeping your device visible for notifications, video calls, or testing mobile apps.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "planner-01",
        "title": "Planner",
        "category": "Accessories",
        "price": 399,
        "rating": "4.9",
        "reviews": 220,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/planner-01.png",
        "gallery": [
            "../Store Product Images/planner-01.png"
        ],
        "description": "Daily productivity planner tailored for software engineers. Plan your sprints, track bugs, and manage your daily goals effectively.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "polo-tshirt-01",
        "title": "Polo Tshirt",
        "category": "T-Shirts",
        "price": 899,
        "rating": "4.7",
        "reviews": 288,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/polo-tshirt-01.png",
        "gallery": [
            "../Store Product Images/polo-tshirt-01.png"
        ],
        "description": "Premium polo t-shirt with an embroidered tech logo. A smart-casual choice for office days, client meetings, or tech conferences.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "pop-socket-01",
        "title": "Pop Socket",
        "category": "Accessories",
        "price": 149,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/pop-socket-01.png",
        "gallery": [
            "../Store Product Images/pop-socket-01.png"
        ],
        "description": "Convenient phone grip and stand featuring a cool developer icon. Enhances your grip and prevents accidental drops.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "portfolio-review-01",
        "title": "Portfolio Review",
        "category": "Services",
        "price": 499,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/portfolio-review-01.png",
        "gallery": [
            "../Store Product Images/portfolio-review-01.png"
        ],
        "description": "Professional review of your developer portfolio and GitHub profile. Get constructive feedback to make your projects stand out to employers.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "portfolio-templates-01",
        "title": "Portfolio Templates",
        "category": "Digital Templates",
        "price": 599,
        "rating": "4.9",
        "reviews": 74,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/portfolio-templates-01.png",
        "gallery": [
            "../Store Product Images/portfolio-templates-01.png"
        ],
        "description": "Responsive and modern portfolio website templates. Showcase your projects and skills with these easily customizable HTML/React templates.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premiere-pro-presets-01",
        "title": "Premiere Pro Presets",
        "category": "Digital Templates",
        "price": 699,
        "rating": "5.0",
        "reviews": 91,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premiere-pro-presets-01.png",
        "gallery": [
            "../Store Product Images/premiere-pro-presets-01.png"
        ],
        "description": "Time-saving Premiere Pro presets including text effects, color grades, and smooth transitions to speed up your video workflow.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-diary-01",
        "title": "Premium Diary",
        "category": "Accessories",
        "price": 499,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-diary-01.png",
        "gallery": [
            "../Store Product Images/premium-diary-01.png"
        ],
        "description": "Elegant leather-bound diary with premium quality paper. Perfect for journaling, brainstorming, and writing down your next big startup idea.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-fonts-collection-01",
        "title": "Premium Fonts Collection",
        "category": "Digital Templates",
        "price": 399,
        "rating": "4.8",
        "reviews": 159,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-fonts-collection-01.png",
        "gallery": [
            "../Store Product Images/premium-fonts-collection-01.png"
        ],
        "description": "A curated collection of modern, developer-friendly fonts for coding and UI design. Includes popular monospaced and sans-serif typefaces.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-pen-01",
        "title": "Premium Pen",
        "category": "Accessories",
        "price": 299,
        "rating": "4.7",
        "reviews": 288,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/premium-pen-01.png",
        "gallery": [
            "../Store Product Images/premium-pen-01.png"
        ],
        "description": "Sleek, smooth-writing premium rollerball pen. A great companion for your notebook and everyday note-taking.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-pen-set-01",
        "title": "Premium Pen Set",
        "category": "Accessories",
        "price": 799,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-pen-set-01.png",
        "gallery": [
            "../Store Product Images/premium-pen-set-01.png"
        ],
        "description": "Luxury pen set presented in a stylish case. Makes for an excellent gift for a fellow developer, manager, or client.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-tshirt-01",
        "title": "Premium Tshirt",
        "category": "T-Shirts",
        "price": 799,
        "rating": "5.0",
        "reviews": 339,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-tshirt-01.png",
        "gallery": [
            "../Store Product Images/premium-tshirt-01.png"
        ],
        "description": "Ultra-soft, premium tri-blend t-shirt. Offers superior fit and unmatched comfort, featuring an exclusive minimalist design.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "react-masterclass-01",
        "title": "React Masterclass",
        "category": "Courses",
        "price": 2999,
        "rating": "4.7",
        "reviews": 390,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/react-masterclass-01.png",
        "gallery": [
            "../Store Product Images/react-masterclass-01.png"
        ],
        "description": "Master React.js from fundamentals to advanced concepts like hooks, context API, Redux, and performance optimization.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "react-notes-pdf-01",
        "title": "React Notes Pdf",
        "category": "E-books",
        "price": 199,
        "rating": "4.5",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/react-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/react-notes-pdf-01.png"
        ],
        "description": "Visual PDF notes covering React components, state management, and lifecycle methods. An excellent quick-revision tool.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "resume-review-01",
        "title": "Resume Review",
        "category": "Services",
        "price": 399,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/resume-review-01.png",
        "gallery": [
            "../Store Product Images/resume-review-01.png"
        ],
        "description": "Detailed resume critique by industry professionals. Learn how to optimize your ATS score and highlight your core technical skills.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "resume-review-02",
        "title": "Resume Review",
        "category": "Services",
        "price": 599,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/resume-review-02.png",
        "gallery": [
            "../Store Product Images/resume-review-02.png"
        ],
        "description": "Premium resume overhaul service. We rewrite and format your resume to maximize your chances of passing recruiter screenings.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "resume-templates-01",
        "title": "Resume Templates",
        "category": "Digital Templates",
        "price": 299,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/resume-templates-01.png",
        "gallery": [
            "../Store Product Images/resume-templates-01.png"
        ],
        "description": "ATS-friendly, professionally designed resume templates. Available in Word, Figma, and LaTeX formats to suit your preference.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "screen-cleaner-01",
        "title": "Screen Cleaner",
        "category": "Accessories",
        "price": 249,
        "rating": "5.0",
        "reviews": 339,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/screen-cleaner-01.png",
        "gallery": [
            "../Store Product Images/screen-cleaner-01.png"
        ],
        "description": "All-in-one screen cleaning kit featuring a microfiber cloth and safe cleaning solution. Keep your monitors and laptops spotless.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "social-media-templates-01",
        "title": "Social Media Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.6",
        "reviews": 125,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/social-media-templates-01.png",
        "gallery": [
            "../Store Product Images/social-media-templates-01.png"
        ],
        "description": "Ready-to-use social media post templates for Instagram, LinkedIn, and Twitter. Perfect for tech influencers and startup pages.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sound-effects-pack-01",
        "title": "Sound Effects Pack",
        "category": "Digital Templates",
        "price": 599,
        "rating": "4.8",
        "reviews": 57,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/sound-effects-pack-01.png",
        "gallery": [
            "../Store Product Images/sound-effects-pack-01.png"
        ],
        "description": "High-quality sound effects library tailored for UI interactions, app notifications, and tech-related video content.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sql-database-course-01",
        "title": "Sql Database Course",
        "category": "Courses",
        "price": 1999,
        "rating": "4.9",
        "reviews": 74,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/sql-database-course-01.png",
        "gallery": [
            "../Store Product Images/sql-database-course-01.png"
        ],
        "description": "Comprehensive guide to SQL and relational databases. Learn complex queries, indexing, normalization, and database design.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sql-notes-pdf-01",
        "title": "Sql Notes Pdf",
        "category": "E-books",
        "price": 149,
        "rating": "4.9",
        "reviews": 322,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/sql-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/sql-notes-pdf-01.png"
        ],
        "description": "Clear and concise PDF notes on SQL syntax and best practices. A handy reference for backend devs and data analysts.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "steel-bottle-01",
        "title": "Steel Bottle",
        "category": "Accessories",
        "price": 699,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/steel-bottle-01.png",
        "gallery": [
            "../Store Product Images/steel-bottle-01.png"
        ],
        "description": "High-grade stainless steel water bottle. Double-wall vacuum insulation keeps your drinks cold or hot during long coding sessions.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sticky-notes-set-01",
        "title": "Sticky Notes Set",
        "category": "Accessories",
        "price": 149,
        "rating": "4.6",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/sticky-notes-set-01.png",
        "gallery": [
            "../Store Product Images/sticky-notes-set-01.png"
        ],
        "description": "Colorful set of sticky notes for brainstorming, kanban boards, and quick reminders. An essential tool for agile planning.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sweatshirt-01",
        "title": "Sweatshirt",
        "category": "Hoodies",
        "price": 1299,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/sweatshirt-01.png",
        "gallery": [
            "../Store Product Images/sweatshirt-01.png"
        ],
        "description": "Classic crewneck sweatshirt with a comfortable, relaxed fit. Features a stylish tech motif for your everyday casual look.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "thumbnail-templates-01",
        "title": "Thumbnail Templates",
        "category": "Digital Templates",
        "price": 299,
        "rating": "4.9",
        "reviews": 74,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/thumbnail-templates-01.png",
        "gallery": [
            "../Store Product Images/thumbnail-templates-01.png"
        ],
        "description": "Eye-catching YouTube thumbnail templates specifically designed for tech tutorials, coding vlogs, and product reviews.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "tote-bag-01",
        "title": "Tote Bag",
        "category": "Accessories",
        "price": 399,
        "rating": "5.0",
        "reviews": 237,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/tote-bag-01.png",
        "gallery": [
            "../Store Product Images/tote-bag-01.png"
        ],
        "description": "Eco-friendly canvas tote bag with a fun programming pun. Great for carrying groceries, books, or your everyday essentials.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "travel-mug-01",
        "title": "Travel Mug",
        "category": "Mugs",
        "price": 599,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/travel-mug-01.png",
        "gallery": [
            "../Store Product Images/travel-mug-01.png"
        ],
        "description": "Spill-proof, insulated travel mug. Keep your coffee piping hot while commuting to the office or working from a cafe.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "tshirt-01",
        "title": "Tshirt",
        "category": "T-Shirts",
        "price": 499,
        "rating": "4.8",
        "reviews": 203,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/tshirt-01.png",
        "gallery": [
            "../Store Product Images/tshirt-01.png"
        ],
        "description": "Our classic flagship developer t-shirt. Soft, breathable cotton featuring the iconic CodeByTushu logo.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "ui-kits-01",
        "title": "Ui Kits",
        "category": "Digital Templates",
        "price": 1499,
        "rating": "4.9",
        "reviews": 220,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/ui-kits-01.png",
        "gallery": [
            "../Store Product Images/ui-kits-01.png"
        ],
        "description": "Massive UI kit containing hundreds of web and mobile components. Speed up your prototyping and design workflow effortlessly.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "usb-hub-01",
        "title": "Usb Hub",
        "category": "Accessories",
        "price": 899,
        "rating": "4.9",
        "reviews": 220,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/usb-hub-01.png",
        "gallery": [
            "../Store Product Images/usb-hub-01.png"
        ],
        "description": "Multi-port USB-C hub adapter. Expand your laptop's connectivity with extra USB-A, HDMI, and card reader slots.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "webcam-cover-01",
        "title": "Webcam Cover",
        "category": "Accessories",
        "price": 99,
        "rating": "4.8",
        "reviews": 305,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/webcam-cover-01.png",
        "gallery": [
            "../Store Product Images/webcam-cover-01.png"
        ],
        "description": "Ultra-thin sliding webcam cover. Protect your privacy and prevent unwanted spying without interfering with laptop closure.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "website-templates-01",
        "title": "Website Templates",
        "category": "Digital Templates",
        "price": 1999,
        "rating": "4.7",
        "reviews": 390,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/website-templates-01.png",
        "gallery": [
            "../Store Product Images/website-templates-01.png"
        ],
        "description": "Premium, fully responsive website templates. Jumpstart your next client project with these beautifully designed themes.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "wrist-rest-01",
        "title": "Wrist Rest",
        "category": "Accessories",
        "price": 349,
        "rating": "4.6",
        "reviews": 271,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/wrist-rest-01.png",
        "gallery": [
            "../Store Product Images/wrist-rest-01.png"
        ],
        "description": "Ergonomic memory foam wrist rest for keyboards. Prevents fatigue and carpal tunnel during intensive typing sessions.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "youtube-intro-templates-01",
        "title": "Youtube Intro Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.7",
        "reviews": 142,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/youtube-intro-templates-01.png",
        "gallery": [
            "../Store Product Images/youtube-intro-templates-01.png"
        ],
        "description": "Dynamic and professional YouTube intro sequences. Grab your audience's attention right from the first second.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    }
];

// Export for module systems (if needed)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = storeData;
}
