const storeData = [
    {
        id: "tshirt-01",
        title: "Developer Mode T-Shirt",
        category: "T-Shirts",
        price: 499,
        rating: 4.8,
        reviews: 120,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/tshirt-01.webp",
        gallery: ["../assets/images/products/tshirt-01.webp"],
        description: "Premium cotton t-shirt with 'Developer Mode: ON' minimal typography. Perfect for long coding sessions.",
        features: ["100% Premium Cotton", "Comfortable fit", "High-quality durable print", "Pre-shrunk fabric"]
    },
    {
        id: "tshirt-02",
        title: "Eat Sleep Code T-Shirt",
        category: "T-Shirts",
        price: 499,
        rating: 4.7,
        reviews: 95,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/tshirt-02.webp",
        gallery: ["../assets/images/products/tshirt-02.webp"],
        description: "The classic mantra for every passionate developer. High-quality print on a soft, breathable fabric.",
        features: ["100% Cotton", "Regular fit", "Breathable fabric"]
    },
    {
        id: "premium-tshirt-01",
        title: "Premium Tech T-Shirt",
        category: "T-Shirts",
        price: 799,
        rating: 4.9,
        reviews: 210,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/premium-tshirt-01.webp",
        gallery: ["../assets/images/products/premium-tshirt-01.webp"],
        description: "Elevate your style with this premium quality t-shirt designed for the modern tech professional.",
        features: ["Supima Cotton", "Tailored fit", "Wrinkle-resistant"]
    },
    {
        id: "oversized-tshirt-01",
        title: "Bug Hunter Oversized T-Shirt",
        category: "T-Shirts",
        price: 699,
        rating: 4.8,
        reviews: 150,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/oversized-tshirt-01.webp",
        gallery: ["../assets/images/products/oversized-tshirt-01.webp"],
        description: "Stay comfortable while debugging. This oversized t-shirt offers maximum comfort with a trendy streetwear look.",
        features: ["Oversized fit", "Heavyweight cotton", "Drop shoulder design"]
    },
    {
        id: "polo-tshirt-01",
        title: "Smart Coder Polo T-Shirt",
        category: "T-Shirts",
        price: 899,
        rating: 4.6,
        reviews: 80,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/polo-tshirt-01.webp",
        gallery: ["../assets/images/products/polo-tshirt-01.webp"],
        description: "A smart-casual polo for meetings or casual Fridays. Features a subtle embroidered code bracket logo.",
        features: ["Pique cotton", "Embroidered logo", "Ribbed collar and cuffs"]
    },
    {
        id: "hoodie-01",
        title: "Night Owl Developer Hoodie",
        category: "Hoodies",
        price: 1299,
        rating: 4.9,
        reviews: 340,
        stockStatus: "in-stock",
        featured: true,
        newArrival: true,
        image: "../assets/images/products/hoodie-01.webp",
        gallery: ["../assets/images/products/hoodie-01.webp"],
        description: "Stay warm during those late-night coding grinds. Fleece-lined interior with a sleek design.",
        features: ["Ultra-soft fleece lining", "Adjustable drawstring hood", "Kangaroo pocket"]
    },
    {
        id: "coffee-mug-01",
        title: "Code Fuel Coffee Mug",
        category: "Mugs",
        price: 299,
        rating: 4.7,
        reviews: 185,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/coffee-mug-01.webp",
        gallery: ["../assets/images/products/coffee-mug-01.webp"],
        description: "Convert coffee into code efficiently with this classic 11oz ceramic mug.",
        features: ["11oz capacity", "Microwave safe", "Dishwasher safe"]
    },
    {
        id: "magic-mug-01",
        title: "Dark Mode Magic Mug",
        category: "Mugs",
        price: 399,
        rating: 4.8,
        reviews: 120,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/magic-mug-01.webp",
        gallery: ["../assets/images/products/magic-mug-01.webp"],
        description: "Pour hot liquid and watch the hidden code appear! A color-changing magic mug for true geeks.",
        features: ["Heat-sensitive coating", "11oz capacity", "Hand wash recommended"]
    },
    {
        id: "travel-mug-01",
        title: "Nomad Developer Travel Mug",
        category: "Mugs",
        price: 499,
        rating: 4.6,
        reviews: 90,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/travel-mug-01.webp",
        gallery: ["../assets/images/products/travel-mug-01.webp"],
        description: "Take your coffee on the go. Insulated travel mug to keep your drinks hot during morning commutes.",
        features: ["Double-wall insulation", "Spill-proof lid", "Fits standard cup holders"]
    },
    {
        id: "steel-bottle-01",
        title: "Stay Hydrated Steel Bottle",
        category: "Accessories",
        price: 599,
        rating: 4.9,
        reviews: 230,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/steel-bottle-01.webp",
        gallery: ["../assets/images/products/steel-bottle-01.webp"],
        description: "Premium stainless steel water bottle. Keeps water cold for 24 hours so you stay hydrated while coding.",
        features: ["Stainless steel", "Vacuum insulated", "Leak-proof"]
    },
    {
        id: "water-bottle-01",
        title: "Minimalist Water Bottle",
        category: "Accessories",
        price: 349,
        rating: 4.5,
        reviews: 75,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/water-bottle-01.webp",
        gallery: ["../assets/images/products/water-bottle-01.webp"],
        description: "A lightweight and durable water bottle with a sleek, minimalist design.",
        features: ["BPA-free plastic", "Lightweight", "Easy to carry"]
    },
    {
        id: "keyboard-stickers-01",
        title: "Shortcut Keys Sticker Pack",
        category: "Stickers",
        price: 149,
        rating: 4.8,
        reviews: 420,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/keyboard-stickers-01.webp",
        gallery: ["../assets/images/products/keyboard-stickers-01.webp"],
        description: "Boost your productivity with these high-quality keyboard shortcut stickers for VS Code and more.",
        features: ["Waterproof vinyl", "Residue-free removal", "Matte finish"]
    },
    {
        id: "developer-quote-stickers-01",
        title: "Dev Quotes Sticker Pack",
        category: "Stickers",
        price: 199,
        rating: 4.9,
        reviews: 310,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/developer-quote-stickers-01.webp",
        gallery: ["../assets/images/products/developer-quote-stickers-01.webp"],
        description: "Decorate your laptop with funny and relatable developer quotes and memes.",
        features: ["Pack of 15 stickers", "Die-cut design", "Durable vinyl"]
    },
    {
        id: "notebook-01",
        title: "Code Architecture Notebook",
        category: "Accessories",
        price: 249,
        rating: 4.7,
        reviews: 110,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/notebook-01.webp",
        gallery: ["../assets/images/products/notebook-01.webp"],
        description: "A dotted grid notebook perfect for sketching out system architectures and algorithms.",
        features: ["A5 size", "Dotted grid pages", "Premium paper quality"]
    },
    {
        id: "premium-diary-01",
        title: "Tech Executive Premium Diary",
        category: "Accessories",
        price: 499,
        rating: 4.8,
        reviews: 85,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/premium-diary-01.webp",
        gallery: ["../assets/images/products/premium-diary-01.webp"],
        description: "A luxurious leather-bound diary for your daily stand-up notes, to-dos, and big ideas.",
        features: ["Faux leather cover", "Ribbon bookmark", "Ruled pages"]
    },
    {
        id: "planner-01",
        title: "Sprint & Goals Planner",
        category: "Accessories",
        price: 399,
        rating: 4.6,
        reviews: 65,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/planner-01.webp",
        gallery: ["../assets/images/products/planner-01.webp"],
        description: "Organize your weeks in sprints. A dedicated planner to track your coding goals, habits, and projects.",
        features: ["Undated planner", "Sprint tracking sections", "Habit tracker"]
    },
    {
        id: "backpack-01",
        title: "Tech Nomad Backpack",
        category: "Accessories",
        price: 1499,
        rating: 4.9,
        reviews: 280,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/backpack-01.webp",
        gallery: ["../assets/images/products/backpack-01.webp"],
        description: "A spacious, water-resistant backpack designed specifically to carry all your tech gear safely.",
        features: ["Water-resistant material", "Padded laptop sleeve", "Multiple compartments"]
    },
    {
        id: "laptop-bag-01",
        title: "Minimalist Laptop Sleeve",
        category: "Accessories",
        price: 799,
        rating: 4.7,
        reviews: 140,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/laptop-bag-01.webp",
        gallery: ["../assets/images/products/laptop-bag-01.webp"],
        description: "Protect your machine with this sleek, slim-profile laptop sleeve. Fits up to 15-inch laptops.",
        features: ["Soft inner lining", "Slim profile", "Water-repellent exterior"]
    },
    {
        id: "mobile-cover-01",
        title: "Circuit Board Mobile Cover",
        category: "Accessories",
        price: 299,
        rating: 4.5,
        reviews: 200,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/mobile-cover-01.webp",
        gallery: ["../assets/images/products/mobile-cover-01.webp"],
        description: "Show off your inner hardware geek with this durable circuit board pattern mobile cover.",
        features: ["Shock-absorbent", "Matte finish", "Precise cutouts"]
    },
    {
        id: "pop-socket-01",
        title: "Terminal Icon Pop Socket",
        category: "Accessories",
        price: 149,
        rating: 4.4,
        reviews: 95,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/pop-socket-01.webp",
        gallery: ["../assets/images/products/pop-socket-01.webp"],
        description: "Get a better grip on your phone with this cool terminal icon pop socket.",
        features: ["Strong adhesive", "Collapsible design", "Comfortable grip"]
    },
    {
        id: "phone-stand-01",
        title: "Aluminum Phone Stand",
        category: "Accessories",
        price: 399,
        rating: 4.8,
        reviews: 155,
        stockStatus: "in-stock",
        featured: false,
        newArrival: true,
        image: "../assets/images/products/phone-stand-01.webp",
        gallery: ["../assets/images/products/phone-stand-01.webp"],
        description: "Keep your phone visible at the perfect angle on your desk while you code.",
        features: ["Premium aluminum", "Adjustable angle", "Anti-slip pads"]
    },
    {
        id: "laptop-stand-01",
        title: "Ergonomic Laptop Stand",
        category: "Accessories",
        price: 999,
        rating: 4.9,
        reviews: 320,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/laptop-stand-01.webp",
        gallery: ["../assets/images/products/laptop-stand-01.webp"],
        description: "Improve your posture with this foldable, adjustable, and sturdy aluminum laptop stand.",
        features: ["Foldable & portable", "Cooling design", "Supports up to 17-inch laptops"]
    },
    {
        id: "usb-hub-01",
        title: "7-in-1 Type-C USB Hub",
        category: "Accessories",
        price: 1299,
        rating: 4.7,
        reviews: 210,
        stockStatus: "in-stock",
        featured: true,
        newArrival: true,
        image: "../assets/images/products/usb-hub-01.webp",
        gallery: ["../assets/images/products/usb-hub-01.webp"],
        description: "Expand your connectivity with this essential 7-in-1 USB-C hub. Perfect for modern ultrabooks.",
        features: ["HDMI output", "USB 3.0 ports", "SD/TF card reader", "PD charging"]
    },
    {
        id: "java-notes-pdf-01",
        title: "Java Mastery Notes",
        category: "E-books",
        price: 199,
        rating: 5.0,
        reviews: 450,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/java-notes-pdf-01.webp",
        gallery: ["../assets/images/products/java-notes-pdf-01.webp"],
        description: "Comprehensive handwritten-style PDF notes for mastering Java from basics to advanced concepts.",
        features: ["Instant PDF Download", "Visual diagrams", "Code snippets included"]
    },
    {
        id: "react-notes-pdf-01",
        title: "React.js Complete Guide",
        category: "E-books",
        price: 249,
        rating: 4.9,
        reviews: 380,
        stockStatus: "in-stock",
        featured: true,
        newArrival: true,
        image: "../assets/images/products/react-notes-pdf-01.webp",
        gallery: ["../assets/images/products/react-notes-pdf-01.webp"],
        description: "Your ultimate resource for learning React. Includes hooks, state management, and best practices.",
        features: ["Instant PDF Download", "Project-based examples", "Cheatsheets included"]
    },
    {
        id: "resume-templates-01",
        title: "ATS-Friendly Resume Templates",
        category: "Digital Templates",
        price: 149,
        rating: 4.8,
        reviews: 275,
        stockStatus: "in-stock",
        featured: false,
        newArrival: false,
        image: "../assets/images/products/resume-templates-01.webp",
        gallery: ["../assets/images/products/resume-templates-01.webp"],
        description: "A collection of 5 highly effective, ATS-friendly resume templates optimized for software engineers.",
        features: ["Word & PDF formats", "ATS optimized", "Cover letter included"]
    },
    {
        id: "portfolio-templates-01",
        title: "Modern Portfolio UI Kit",
        category: "Digital Templates",
        price: 499,
        rating: 4.9,
        reviews: 190,
        stockStatus: "in-stock",
        featured: true,
        newArrival: false,
        image: "../assets/images/products/portfolio-templates-01.webp",
        gallery: ["../assets/images/products/portfolio-templates-01.webp"],
        description: "A premium, fully responsive portfolio template built with Next.js and Tailwind CSS.",
        features: ["Next.js & Tailwind", "Dark/Light Mode", "Easy to customize"]
    }
];

function getProductById(id) {
    return storeData.find(p => p.id === id);
}

function getAllProducts() {
    return storeData;
}

function getFeaturedProducts() {
    return storeData.filter(p => p.featured);
}

function getNewArrivals() {
    return storeData.filter(p => p.newArrival);
}

