/**
 * CodeByTushu Store - Product Data
 * Auto-generated by script
 */

const storeData = [
    {
        "id": "tshirt-01",
        "title": "Tshirt",
        "category": "T-Shirts",
        "price": 499,
        "rating": "4.6",
        "reviews": 327,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": true,
        "image": "../Store Product Images/tshirt-01.png",
        "gallery": [
            "../Store Product Images/tshirt-01.png"
        ],
        "description": "Premium quality Tshirt for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "tshirt-02",
        "title": "Tshirt 2",
        "category": "T-Shirts",
        "price": 499,
        "rating": "4.6",
        "reviews": 383,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/tshirt-02.png",
        "gallery": [
            "../Store Product Images/tshirt-02.png"
        ],
        "description": "Premium quality Tshirt for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-tshirt-01",
        "title": "Premium Tshirt",
        "category": "T-Shirts",
        "price": 799,
        "rating": "5.0",
        "reviews": 222,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-tshirt-01.png",
        "gallery": [
            "../Store Product Images/premium-tshirt-01.png"
        ],
        "description": "Premium quality Premium Tshirt for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "oversized-tshirt-01",
        "title": "Oversized Tshirt",
        "category": "T-Shirts",
        "price": 699,
        "rating": "4.6",
        "reviews": 150,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/oversized-tshirt-01.png",
        "gallery": [
            "../Store Product Images/oversized-tshirt-01.png"
        ],
        "description": "Premium quality Oversized Tshirt for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "polo-tshirt-01",
        "title": "Polo Tshirt",
        "category": "T-Shirts",
        "price": 899,
        "rating": "4.9",
        "reviews": 231,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/polo-tshirt-01.png",
        "gallery": [
            "../Store Product Images/polo-tshirt-01.png"
        ],
        "description": "Premium quality Polo Tshirt for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "hoodie-01",
        "title": "Hoodie",
        "category": "Hoodies",
        "price": 1299,
        "rating": "4.6",
        "reviews": 172,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/hoodie-01.png",
        "gallery": [
            "../Store Product Images/hoodie-01.png"
        ],
        "description": "Premium quality Hoodie for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "coffee-mug-01",
        "title": "Coffee Mug",
        "category": "Mugs",
        "price": 299,
        "rating": "4.7",
        "reviews": 418,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/coffee-mug-01.png",
        "gallery": [
            "../Store Product Images/coffee-mug-01.png"
        ],
        "description": "Premium quality Coffee Mug for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "magic-mug-01",
        "title": "Magic Mug",
        "category": "Mugs",
        "price": 399,
        "rating": "4.9",
        "reviews": 380,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/magic-mug-01.png",
        "gallery": [
            "../Store Product Images/magic-mug-01.png"
        ],
        "description": "Premium quality Magic Mug for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "steel-bottle-01",
        "title": "Steel Bottle",
        "category": "Accessories",
        "price": 599,
        "rating": "4.6",
        "reviews": 63,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/steel-bottle-01.png",
        "gallery": [
            "../Store Product Images/steel-bottle-01.png"
        ],
        "description": "Premium quality Steel Bottle for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "water-bottle-01",
        "title": "Water Bottle",
        "category": "Accessories",
        "price": 349,
        "rating": "4.6",
        "reviews": 50,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/water-bottle-01.png",
        "gallery": [
            "../Store Product Images/water-bottle-01.png"
        ],
        "description": "Premium quality Water Bottle for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "travel-mug-01",
        "title": "Travel Mug",
        "category": "Mugs",
        "price": 499,
        "rating": "4.6",
        "reviews": 221,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/travel-mug-01.png",
        "gallery": [
            "../Store Product Images/travel-mug-01.png"
        ],
        "description": "Premium quality Travel Mug for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "notebook-01",
        "title": "Notebook",
        "category": "Accessories",
        "price": 249,
        "rating": "4.5",
        "reviews": 284,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/notebook-01.png",
        "gallery": [
            "../Store Product Images/notebook-01.png"
        ],
        "description": "Premium quality Notebook for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-diary-01",
        "title": "Premium Diary",
        "category": "Accessories",
        "price": 499,
        "rating": "4.7",
        "reviews": 277,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premium-diary-01.png",
        "gallery": [
            "../Store Product Images/premium-diary-01.png"
        ],
        "description": "Premium quality Premium Diary for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "planner-01",
        "title": "Planner",
        "category": "Accessories",
        "price": 399,
        "rating": "4.5",
        "reviews": 183,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/planner-01.png",
        "gallery": [
            "../Store Product Images/planner-01.png"
        ],
        "description": "Premium quality Planner for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "backpack-01",
        "title": "Backpack",
        "category": "Accessories",
        "price": 1499,
        "rating": "4.8",
        "reviews": 281,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/backpack-01.png",
        "gallery": [
            "../Store Product Images/backpack-01.png"
        ],
        "description": "Premium quality Backpack for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-bag-01",
        "title": "Laptop Bag",
        "category": "Accessories",
        "price": 799,
        "rating": "4.6",
        "reviews": 130,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/laptop-bag-01.png",
        "gallery": [
            "../Store Product Images/laptop-bag-01.png"
        ],
        "description": "Premium quality Laptop Bag for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mobile-cover-01",
        "title": "Mobile Cover",
        "category": "Accessories",
        "price": 299,
        "rating": "4.7",
        "reviews": 297,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mobile-cover-01.png",
        "gallery": [
            "../Store Product Images/mobile-cover-01.png"
        ],
        "description": "Premium quality Mobile Cover for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "pop-socket-01",
        "title": "Pop Socket",
        "category": "Accessories",
        "price": 149,
        "rating": "4.6",
        "reviews": 328,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/pop-socket-01.png",
        "gallery": [
            "../Store Product Images/pop-socket-01.png"
        ],
        "description": "Premium quality Pop Socket for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "phone-stand-01",
        "title": "Phone Stand",
        "category": "Accessories",
        "price": 399,
        "rating": "4.9",
        "reviews": 331,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/phone-stand-01.png",
        "gallery": [
            "../Store Product Images/phone-stand-01.png"
        ],
        "description": "Premium quality Phone Stand for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "laptop-stand-01",
        "title": "Laptop Stand",
        "category": "Accessories",
        "price": 999,
        "rating": "4.9",
        "reviews": 201,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/laptop-stand-01.png",
        "gallery": [
            "../Store Product Images/laptop-stand-01.png"
        ],
        "description": "Premium quality Laptop Stand for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "usb-hub-01",
        "title": "Usb Hub",
        "category": "Accessories",
        "price": 1299,
        "rating": "4.7",
        "reviews": 196,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/usb-hub-01.png",
        "gallery": [
            "../Store Product Images/usb-hub-01.png"
        ],
        "description": "Premium quality Usb Hub for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "keyboard-stickers-01",
        "title": "Keyboard Stickers",
        "category": "Stickers",
        "price": 149,
        "rating": "5.0",
        "reviews": 365,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/keyboard-stickers-01.png",
        "gallery": [
            "../Store Product Images/keyboard-stickers-01.png"
        ],
        "description": "Premium quality Keyboard Stickers for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "developer-stickers-01",
        "title": "Developer Stickers",
        "category": "Stickers",
        "price": 199,
        "rating": "4.8",
        "reviews": 265,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/developer-stickers-01.png",
        "gallery": [
            "../Store Product Images/developer-stickers-01.png"
        ],
        "description": "Premium quality Developer Stickers for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mouse-pad-01",
        "title": "Mouse Pad",
        "category": "Accessories",
        "price": 299,
        "rating": "5.0",
        "reviews": 81,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mouse-pad-01.png",
        "gallery": [
            "../Store Product Images/mouse-pad-01.png"
        ],
        "description": "Premium quality Mouse Pad for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "extended-mouse-pad-01",
        "title": "Extended Mouse Pad",
        "category": "Accessories",
        "price": 599,
        "rating": "4.7",
        "reviews": 337,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/extended-mouse-pad-01.png",
        "gallery": [
            "../Store Product Images/extended-mouse-pad-01.png"
        ],
        "description": "Premium quality Extended Mouse Pad for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-mat-01",
        "title": "Desk Mat",
        "category": "Accessories",
        "price": 899,
        "rating": "4.8",
        "reviews": 370,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/desk-mat-01.png",
        "gallery": [
            "../Store Product Images/desk-mat-01.png"
        ],
        "description": "Premium quality Desk Mat for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "poster-01",
        "title": "Poster",
        "category": "Accessories",
        "price": 249,
        "rating": "4.7",
        "reviews": 96,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/poster-01.png",
        "gallery": [
            "../Store Product Images/poster-01.png"
        ],
        "description": "Premium quality Poster for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "framed-poster-01",
        "title": "Framed Poster",
        "category": "Accessories",
        "price": 699,
        "rating": "4.6",
        "reviews": 176,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/framed-poster-01.png",
        "gallery": [
            "../Store Product Images/framed-poster-01.png"
        ],
        "description": "Premium quality Framed Poster for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "wall-art-01",
        "title": "Wall Art",
        "category": "Accessories",
        "price": 899,
        "rating": "4.5",
        "reviews": 273,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/wall-art-01.png",
        "gallery": [
            "../Store Product Images/wall-art-01.png"
        ],
        "description": "Premium quality Wall Art for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "pen-drive-01",
        "title": "Pen Drive",
        "category": "Accessories",
        "price": 499,
        "rating": "4.5",
        "reviews": 95,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/pen-drive-01.png",
        "gallery": [
            "../Store Product Images/pen-drive-01.png"
        ],
        "description": "Premium quality Pen Drive for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "hard-drive-01",
        "title": "Hard Drive",
        "category": "Accessories",
        "price": 3999,
        "rating": "4.8",
        "reviews": 354,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/hard-drive-01.png",
        "gallery": [
            "../Store Product Images/hard-drive-01.png"
        ],
        "description": "Premium quality Hard Drive for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "power-bank-01",
        "title": "Power Bank",
        "category": "Accessories",
        "price": 1299,
        "rating": "4.9",
        "reviews": 141,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/power-bank-01.png",
        "gallery": [
            "../Store Product Images/power-bank-01.png"
        ],
        "description": "Premium quality Power Bank for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "cable-organizer-01",
        "title": "Cable Organizer",
        "category": "Accessories",
        "price": 299,
        "rating": "4.8",
        "reviews": 228,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/cable-organizer-01.png",
        "gallery": [
            "../Store Product Images/cable-organizer-01.png"
        ],
        "description": "Premium quality Cable Organizer for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-organizer-01",
        "title": "Desk Organizer",
        "category": "Accessories",
        "price": 499,
        "rating": "4.5",
        "reviews": 290,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-organizer-01.png",
        "gallery": [
            "../Store Product Images/desk-organizer-01.png"
        ],
        "description": "Premium quality Desk Organizer for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "headphones-stand-01",
        "title": "Headphones Stand",
        "category": "Accessories",
        "price": 599,
        "rating": "4.6",
        "reviews": 381,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/headphones-stand-01.png",
        "gallery": [
            "../Store Product Images/headphones-stand-01.png"
        ],
        "description": "Premium quality Headphones Stand for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "webcam-cover-01",
        "title": "Webcam Cover",
        "category": "Accessories",
        "price": 149,
        "rating": "4.9",
        "reviews": 220,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": true,
        "image": "../Store Product Images/webcam-cover-01.png",
        "gallery": [
            "../Store Product Images/webcam-cover-01.png"
        ],
        "description": "Premium quality Webcam Cover for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "screen-cleaner-01",
        "title": "Screen Cleaner",
        "category": "Accessories",
        "price": 199,
        "rating": "4.6",
        "reviews": 65,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/screen-cleaner-01.png",
        "gallery": [
            "../Store Product Images/screen-cleaner-01.png"
        ],
        "description": "Premium quality Screen Cleaner for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "monitor-lamp-01",
        "title": "Monitor Lamp",
        "category": "Accessories",
        "price": 1499,
        "rating": "4.8",
        "reviews": 187,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/monitor-lamp-01.png",
        "gallery": [
            "../Store Product Images/monitor-lamp-01.png"
        ],
        "description": "Premium quality Monitor Lamp for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "ring-light-01",
        "title": "Ring Light",
        "category": "Accessories",
        "price": 899,
        "rating": "4.9",
        "reviews": 301,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/ring-light-01.png",
        "gallery": [
            "../Store Product Images/ring-light-01.png"
        ],
        "description": "Premium quality Ring Light for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "microphone-01",
        "title": "Microphone",
        "category": "Accessories",
        "price": 2499,
        "rating": "4.9",
        "reviews": 190,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/microphone-01.png",
        "gallery": [
            "../Store Product Images/microphone-01.png"
        ],
        "description": "Premium quality Microphone for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mechanical-keyboard-01",
        "title": "Mechanical Keyboard",
        "category": "Accessories",
        "price": 4999,
        "rating": "4.9",
        "reviews": 135,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/mechanical-keyboard-01.png",
        "gallery": [
            "../Store Product Images/mechanical-keyboard-01.png"
        ],
        "description": "Premium quality Mechanical Keyboard for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "wireless-mouse-01",
        "title": "Wireless Mouse",
        "category": "Accessories",
        "price": 999,
        "rating": "5.0",
        "reviews": 253,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/wireless-mouse-01.png",
        "gallery": [
            "../Store Product Images/wireless-mouse-01.png"
        ],
        "description": "Premium quality Wireless Mouse for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "wrist-rest-01",
        "title": "Wrist Rest",
        "category": "Accessories",
        "price": 399,
        "rating": "4.6",
        "reviews": 241,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/wrist-rest-01.png",
        "gallery": [
            "../Store Product Images/wrist-rest-01.png"
        ],
        "description": "Premium quality Wrist Rest for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "blue-light-glasses-01",
        "title": "Blue Light Glasses",
        "category": "Accessories",
        "price": 899,
        "rating": "4.8",
        "reviews": 324,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/blue-light-glasses-01.png",
        "gallery": [
            "../Store Product Images/blue-light-glasses-01.png"
        ],
        "description": "Premium quality Blue Light Glasses for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "ergonomic-chair-01",
        "title": "Ergonomic Chair",
        "category": "Accessories",
        "price": 7999,
        "rating": "4.8",
        "reviews": 379,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/ergonomic-chair-01.png",
        "gallery": [
            "../Store Product Images/ergonomic-chair-01.png"
        ],
        "description": "Premium quality Ergonomic Chair for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "standing-desk-01",
        "title": "Standing Desk",
        "category": "Accessories",
        "price": 14999,
        "rating": "4.6",
        "reviews": 406,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/standing-desk-01.png",
        "gallery": [
            "../Store Product Images/standing-desk-01.png"
        ],
        "description": "Premium quality Standing Desk for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "foot-rest-01",
        "title": "Foot Rest",
        "category": "Accessories",
        "price": 999,
        "rating": "4.5",
        "reviews": 295,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/foot-rest-01.png",
        "gallery": [
            "../Store Product Images/foot-rest-01.png"
        ],
        "description": "Premium quality Foot Rest for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "coffee-coasters-01",
        "title": "Coffee Coasters",
        "category": "Accessories",
        "price": 199,
        "rating": "4.7",
        "reviews": 55,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/coffee-coasters-01.png",
        "gallery": [
            "../Store Product Images/coffee-coasters-01.png"
        ],
        "description": "Premium quality Coffee Coasters for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "desk-plant-01",
        "title": "Desk Plant",
        "category": "Accessories",
        "price": 349,
        "rating": "4.9",
        "reviews": 227,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/desk-plant-01.png",
        "gallery": [
            "../Store Product Images/desk-plant-01.png"
        ],
        "description": "Premium quality Desk Plant for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "neon-sign-01",
        "title": "Neon Sign",
        "category": "Accessories",
        "price": 1999,
        "rating": "4.8",
        "reviews": 337,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/neon-sign-01.png",
        "gallery": [
            "../Store Product Images/neon-sign-01.png"
        ],
        "description": "Premium quality Neon Sign for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "java-notes-pdf-01",
        "title": "Java Notes (PDF)",
        "category": "E-books",
        "price": 199,
        "rating": "4.9",
        "reviews": 151,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/java-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/java-notes-pdf-01.png"
        ],
        "description": "Premium quality Java Notes Pdf for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "react-notes-pdf-01",
        "title": "React Notes (PDF)",
        "category": "E-books",
        "price": 249,
        "rating": "4.8",
        "reviews": 421,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/react-notes-pdf-01.png",
        "gallery": [
            "../Store Product Images/react-notes-pdf-01.png"
        ],
        "description": "Premium quality React Notes Pdf for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "resume-templates-01",
        "title": "Resume Templates",
        "category": "Digital Templates",
        "price": 149,
        "rating": "5.0",
        "reviews": 275,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/resume-templates-01.png",
        "gallery": [
            "../Store Product Images/resume-templates-01.png"
        ],
        "description": "Premium quality Resume Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "portfolio-templates-01",
        "title": "Portfolio Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.7",
        "reviews": 246,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/portfolio-templates-01.png",
        "gallery": [
            "../Store Product Images/portfolio-templates-01.png"
        ],
        "description": "Premium quality Portfolio Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "thumbnail-templates-01",
        "title": "Thumbnail Templates",
        "category": "Digital Templates",
        "price": 299,
        "rating": "4.7",
        "reviews": 166,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/thumbnail-templates-01.png",
        "gallery": [
            "../Store Product Images/thumbnail-templates-01.png"
        ],
        "description": "Premium quality Thumbnail Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "api-collection-01",
        "title": "Api Collection",
        "category": "Digital Templates",
        "price": 399,
        "rating": "4.8",
        "reviews": 432,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/api-collection-01.png",
        "gallery": [
            "../Store Product Images/api-collection-01.png"
        ],
        "description": "Premium quality Api Collection for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "html-css-templates-01",
        "title": "Html Css Templates",
        "category": "Digital Templates",
        "price": 199,
        "rating": "4.9",
        "reviews": 101,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/html-css-templates-01.png",
        "gallery": [
            "../Store Product Images/html-css-templates-01.png"
        ],
        "description": "Premium quality Html Css Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "cheat-sheets-01",
        "title": "Cheat Sheets",
        "category": "E-books",
        "price": 99,
        "rating": "4.8",
        "reviews": 139,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/cheat-sheets-01.png",
        "gallery": [
            "../Store Product Images/cheat-sheets-01.png"
        ],
        "description": "Premium quality Cheat Sheets for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "e-book-collection-01",
        "title": "E Book Collection",
        "category": "E-books",
        "price": 499,
        "rating": "4.6",
        "reviews": 406,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/e-book-collection-01.png",
        "gallery": [
            "../Store Product Images/e-book-collection-01.png"
        ],
        "description": "Premium quality E Book Collection for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "java-masterclass-01",
        "title": "Java Masterclass",
        "category": "Courses",
        "price": 999,
        "rating": "4.7",
        "reviews": 255,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/java-masterclass-01.png",
        "gallery": [
            "../Store Product Images/java-masterclass-01.png"
        ],
        "description": "Premium quality Java Masterclass for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "javascript-masterclass-01",
        "title": "Javascript Masterclass",
        "category": "Courses",
        "price": 999,
        "rating": "4.8",
        "reviews": 112,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/javascript-masterclass-01.png",
        "gallery": [
            "../Store Product Images/javascript-masterclass-01.png"
        ],
        "description": "Premium quality Javascript Masterclass for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "react-masterclass-01",
        "title": "React Masterclass",
        "category": "Courses",
        "price": 1299,
        "rating": "4.7",
        "reviews": 60,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/react-masterclass-01.png",
        "gallery": [
            "../Store Product Images/react-masterclass-01.png"
        ],
        "description": "Premium quality React Masterclass for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "nodejs-masterclass-01",
        "title": "Nodejs Masterclass",
        "category": "Courses",
        "price": 1299,
        "rating": "4.9",
        "reviews": 158,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/nodejs-masterclass-01.png",
        "gallery": [
            "../Store Product Images/nodejs-masterclass-01.png"
        ],
        "description": "Premium quality Nodejs Masterclass for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "full-stack-web-development-01",
        "title": "Full Stack Web Development",
        "category": "Courses",
        "price": 2999,
        "rating": "4.6",
        "reviews": 300,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/full-stack-web-development-01.png",
        "gallery": [
            "../Store Product Images/full-stack-web-development-01.png"
        ],
        "description": "Premium quality Full Stack Web Development for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "dsa-course-01",
        "title": "Dsa Course",
        "category": "Courses",
        "price": 1499,
        "rating": "4.8",
        "reviews": 203,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/dsa-course-01.png",
        "gallery": [
            "../Store Product Images/dsa-course-01.png"
        ],
        "description": "Premium quality Dsa Course for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sql-database-course-01",
        "title": "Sql Database Course",
        "category": "Courses",
        "price": 799,
        "rating": "5.0",
        "reviews": 356,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/sql-database-course-01.png",
        "gallery": [
            "../Store Product Images/sql-database-course-01.png"
        ],
        "description": "Premium quality Sql Database Course for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "interview-preparation-01",
        "title": "Interview Preparation",
        "category": "Courses",
        "price": 899,
        "rating": "4.6",
        "reviews": 151,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/interview-preparation-01.png",
        "gallery": [
            "../Store Product Images/interview-preparation-01.png"
        ],
        "description": "Premium quality Interview Preparation for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "devops-course-01",
        "title": "Devops Course",
        "category": "Courses",
        "price": 1999,
        "rating": "4.6",
        "reviews": 307,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/devops-course-01.png",
        "gallery": [
            "../Store Product Images/devops-course-01.png"
        ],
        "description": "Premium quality Devops Course for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "linux-course-01",
        "title": "Linux Course",
        "category": "Courses",
        "price": 699,
        "rating": "4.6",
        "reviews": 446,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/linux-course-01.png",
        "gallery": [
            "../Store Product Images/linux-course-01.png"
        ],
        "description": "Premium quality Linux Course for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premiere-pro-presets-01",
        "title": "Premiere Pro Presets",
        "category": "Digital Templates",
        "price": 399,
        "rating": "4.8",
        "reviews": 325,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/premiere-pro-presets-01.png",
        "gallery": [
            "../Store Product Images/premiere-pro-presets-01.png"
        ],
        "description": "Premium quality Premiere Pro Presets for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "after-effects-templates-01",
        "title": "After Effects Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.6",
        "reviews": 53,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": true,
        "image": "../Store Product Images/after-effects-templates-01.png",
        "gallery": [
            "../Store Product Images/after-effects-templates-01.png"
        ],
        "description": "Premium quality After Effects Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "motion-graphics-pack-01",
        "title": "Motion Graphics Pack",
        "category": "Digital Templates",
        "price": 599,
        "rating": "4.6",
        "reviews": 72,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/motion-graphics-pack-01.png",
        "gallery": [
            "../Store Product Images/motion-graphics-pack-01.png"
        ],
        "description": "Premium quality Motion Graphics Pack for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "thumbnail-templates-02",
        "title": "Thumbnail Templates 2",
        "category": "Digital Templates",
        "price": 299,
        "rating": "4.7",
        "reviews": 298,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/thumbnail-templates-02.png",
        "gallery": [
            "../Store Product Images/thumbnail-templates-02.png"
        ],
        "description": "Premium quality Thumbnail Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "youtube-intro-templates-01",
        "title": "Youtube Intro Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.5",
        "reviews": 218,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/youtube-intro-templates-01.png",
        "gallery": [
            "../Store Product Images/youtube-intro-templates-01.png"
        ],
        "description": "Premium quality Youtube Intro Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "lower-thirds-01",
        "title": "Lower Thirds",
        "category": "Digital Templates",
        "price": 199,
        "rating": "4.7",
        "reviews": 443,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/lower-thirds-01.png",
        "gallery": [
            "../Store Product Images/lower-thirds-01.png"
        ],
        "description": "Premium quality Lower Thirds for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "sound-effects-pack-01",
        "title": "Sound Effects Pack",
        "category": "Digital Templates",
        "price": 299,
        "rating": "4.8",
        "reviews": 127,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/sound-effects-pack-01.png",
        "gallery": [
            "../Store Product Images/sound-effects-pack-01.png"
        ],
        "description": "Premium quality Sound Effects Pack for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "luts-01",
        "title": "Luts",
        "category": "Digital Templates",
        "price": 399,
        "rating": "5.0",
        "reviews": 375,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/luts-01.png",
        "gallery": [
            "../Store Product Images/luts-01.png"
        ],
        "description": "Premium quality Luts for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "premium-fonts-collection-01",
        "title": "Premium Fonts Collection",
        "category": "Digital Templates",
        "price": 249,
        "rating": "4.6",
        "reviews": 389,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/premium-fonts-collection-01.png",
        "gallery": [
            "../Store Product Images/premium-fonts-collection-01.png"
        ],
        "description": "Premium quality Premium Fonts Collection for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "icons-pack-01",
        "title": "Icons Pack",
        "category": "Digital Templates",
        "price": 199,
        "rating": "4.7",
        "reviews": 204,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/icons-pack-01.png",
        "gallery": [
            "../Store Product Images/icons-pack-01.png"
        ],
        "description": "Premium quality Icons Pack for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "figma-templates-01",
        "title": "Figma Templates",
        "category": "Digital Templates",
        "price": 499,
        "rating": "4.5",
        "reviews": 373,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/figma-templates-01.png",
        "gallery": [
            "../Store Product Images/figma-templates-01.png"
        ],
        "description": "Premium quality Figma Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "ui-kits-01",
        "title": "Ui Kits",
        "category": "Digital Templates",
        "price": 799,
        "rating": "4.7",
        "reviews": 129,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/ui-kits-01.png",
        "gallery": [
            "../Store Product Images/ui-kits-01.png"
        ],
        "description": "Premium quality Ui Kits for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "website-templates-01",
        "title": "Website Templates",
        "category": "Digital Templates",
        "price": 999,
        "rating": "4.6",
        "reviews": 323,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/website-templates-01.png",
        "gallery": [
            "../Store Product Images/website-templates-01.png"
        ],
        "description": "Premium quality Website Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "landing-page-templates-01",
        "title": "Landing Page Templates",
        "category": "Digital Templates",
        "price": 599,
        "rating": "5.0",
        "reviews": 380,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/landing-page-templates-01.png",
        "gallery": [
            "../Store Product Images/landing-page-templates-01.png"
        ],
        "description": "Premium quality Landing Page Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "social-media-templates-01",
        "title": "Social Media Templates",
        "category": "Digital Templates",
        "price": 399,
        "rating": "4.7",
        "reviews": 293,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/social-media-templates-01.png",
        "gallery": [
            "../Store Product Images/social-media-templates-01.png"
        ],
        "description": "Premium quality Social Media Templates for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mentorship-01",
        "title": "Mentorship",
        "category": "Services",
        "price": 1999,
        "rating": "4.7",
        "reviews": 66,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": true,
        "image": "../Store Product Images/mentorship-01.png",
        "gallery": [
            "../Store Product Images/mentorship-01.png"
        ],
        "description": "Premium quality Mentorship for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "resume-review-01",
        "title": "Resume Review",
        "category": "Services",
        "price": 499,
        "rating": "4.6",
        "reviews": 192,
        "stockStatus": "in-stock",
        "featured": true,
        "newArrival": false,
        "image": "../Store Product Images/resume-review-01.png",
        "gallery": [
            "../Store Product Images/resume-review-01.png"
        ],
        "description": "Premium quality Resume Review for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "mock-interview-01",
        "title": "Mock Interview",
        "category": "Services",
        "price": 999,
        "rating": "4.9",
        "reviews": 219,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/mock-interview-01.png",
        "gallery": [
            "../Store Product Images/mock-interview-01.png"
        ],
        "description": "Premium quality Mock Interview for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "portfolio-review-01",
        "title": "Portfolio Review",
        "category": "Services",
        "price": 799,
        "rating": "5.0",
        "reviews": 188,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/portfolio-review-01.png",
        "gallery": [
            "../Store Product Images/portfolio-review-01.png"
        ],
        "description": "Premium quality Portfolio Review for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "career-guidance-01",
        "title": "Career Guidance",
        "category": "Services",
        "price": 899,
        "rating": "4.8",
        "reviews": 270,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/career-guidance-01.png",
        "gallery": [
            "../Store Product Images/career-guidance-01.png"
        ],
        "description": "Premium quality Career Guidance for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    },
    {
        "id": "freelancing-consultation-01",
        "title": "Freelancing Consultation",
        "category": "Services",
        "price": 1499,
        "rating": "4.7",
        "reviews": 289,
        "stockStatus": "in-stock",
        "featured": false,
        "newArrival": false,
        "image": "../Store Product Images/freelancing-consultation-01.png",
        "gallery": [
            "../Store Product Images/freelancing-consultation-01.png"
        ],
        "description": "Premium quality Freelancing Consultation for developers, designers, and tech enthusiasts. Boost your productivity and style with CodeByTushu.",
        "features": [
            "Premium Quality",
            "Modern Design",
            "Developer Friendly",
            "Perfect for Workspaces",
            "Fast Delivery"
        ]
    }
];

// ─── Helper Functions ──────────────────────────────────────────────────────────

function getProductById(id) {
    return storeData.find(p => p.id === id);
}

function getAllProducts() {
    return storeData;
}

function getFeaturedProducts() {
    return storeData.filter(p => p.featured);
}

function getNewArrivals() {
    return storeData.filter(p => p.newArrival);
}
